name: Make
description: Build project with make
inputs:
  args:
    description: Arguments to make command
    required: false
    default: ""
runs:
  using: composite
  steps:
    - run: "make ${{ inputs.args }}"
      shell: bash
